### ISSUE TITLE
Adjust Canonical Link Functionality

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/hugo-component-tnd-seo#10]
Needs to accomodate  Midis's issue https://github.com/theNewDynamic/midisgroup.com/issues/227

I think the best way to handle this is to give the user the ability (from within the SEO section of an entry) a select field to choose an entry and we convert that to a link. 

Perhaps that's the only time we need the canonical link (which is not what I said in the original issue), but might be best and cleanest.

**Comment by regisphilibert** [comment]
There is a few things to take into consideration before making this a global feature. 

### 1 We need to GetPage with a parameter which is not GetPage ready
Like `/en/something/something.md`. We usually use our own `func/GetPage` for that, but it might not be available to us if the `tnd-func` component is not been used. 
So we need to check for the existence of GetPage and if not found, either cook our own solution (real pain: GetPage relies on FormatPath etc..., these are complex stuff) or simply throw an error inviting dev to install `tnd-func`.

### 2 Making sure the parameter is not a relative URL vs a relative path: 
`"canonical": "/affiliates"`
Because some projects will have used a string and have for `canonical` value a relative URL, we must make sure to differentiate a relative URL from a file path. In a forestry context, file paths are really file paths, they mention the .md.
But, if a relative URL like `/something` has been previously set as a `canonical` value, the updated component will use`GetPage` on it and return a page which might not systematically be the intended one (URL don't always align with file paths).
There is no way to guess the initial intention of the user. So we'll have to pick side. It will have to either be a "selected" page or a "relative url".

The above might mean we'll need to update content files from project already using the canonical feature. Might not be a lot...

**Comment by budparr** [comment]
would be easier to just use something in Midis for now? I think it would be fine, just need a slightly different naming convention.

**Comment by regisphilibert** [comment]
I'll edit the `tnd-seo/extend.html` file of Midis.

**Comment by budparr** [comment]
Sorry for the wild goose chase. I just assumed anything we did SEO-wise would be better in the component

**Comment by regisphilibert** [comment]
And I agree, we're just a bit in rush on Midis, and I think we need to think this through a bit longer for the component.

**Comment by budparr** [comment]
I'll leave the issue open, but took off backlog, etc.
