### ISSUE TITLE
Invalid top level element "string"

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/hugo-component-tnd-seo#8]
This is an "unparsable structured data" error in Google Search Console.

https://search.google.com/search-console/unknown-type/drilldown?resource_id=sc-domain%3Afreshebt.com&item_key=CgoIJRoGc3RyaW5nEAMYDg&hl=en

**Comment by regisphilibert** [comment]
That was fixed by https://github.com/theNewDynamic/hugo-component-tnd-seo/commit/4af259ec2770087dd1e9d5e0c2af5db3d0ea4bd4 but FreshEBT for some reason was did not have this piece of code. 

Might have commited a wrong change out of this repo's master, but FreshEBT was tracking this wrong commit.

My bad.
